services:
  # orders-service:
  #   build: ./
  #   container_name: orders-service
  #   hostname: orders-service
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 5000:5000
  #   image: orders-service
  #   depends_on:
  #     postgresql:
  #       condition: service_healthy
  #   networks:
  #     - orders_net

  postgresql:
    container_name: orders_pgdb
    hostname: orders_pgdb
    image: postgres:16.2-alpine
    command: postgres -c 'max_connections=200'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: orders
      PGPASSWORD: admin
      PGUSER: orders
      PGDATABASE: ordersdb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql:/data
      - ./docker/postgresql-init:/docker-entrypoint-initdb.d
    networks:
      - orders_net

networks:
  orders_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24